apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/dg-bee/bdd-rsc-1554108569:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/dg-bee/bdd-rsc-1554108569:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-rsc-1554108569
        chartPath: charts/bdd-rsc-1554108569
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/dg-bee/bdd-rsc-1554108569'
          image.tag: '{{.DIGEST_HEX}}'
